### ISSUE TITLE
4.0.1 generating invalid local in animation

### ISSUE THREAD

**Issue by gpoitch** [css-modules/postcss-modules-local-by-default#59]
Since 4.0.1, getting this `:local` injected which wasn't there before.
Input:  
```css
animation: fade .2s var(--easeOutQuart) .1s forwards
```
Output:
```css
animation: fade .2s var(:local(--easeOutQuart)) .1s forwards
```

Found this when updating css-loader. This package is a sub-dep. Works correctly when I override and lock it at 4.0.0

Edit: maybe related to the `var`, not animation specific.

**Comment by alexander-akait** [comment]
Yeah, I think we have this bug before too... we should skip any functions here, I will send a fix soon

**Comment by alexander-akait** [comment]
Fix - https://github.com/css-modules/postcss-modules-local-by-default/pull/60, good new - I found some perf bottlenecks, so it will be a little bit faster :smile:

**Comment by alexander-akait** [comment]
Fixed https://github.com/css-modules/postcss-modules-local-by-default/releases/tag/v4.0.2
